# Generated by Django 5.2.7 on 2025-11-02 16:57

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='profile',
            field=models.FileField(blank=True, null=True, upload_to=user.models.user_profile_path),
        ),
    ]
