# Generated by Django 5.2.7 on 2025-11-02 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_customuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='preferences',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserPreferences',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
